name: pre-release

on:
  pull_request:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Lint
        uses: creyD/prettier_action@v2.2
        with:
          dry: true
          prettier_options: --write .
